<!-- Sistema basico utilizado por programador @Michaell_Mendoza(@dante)  -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../assets/css/inicio.css">
    <title>Inicio</title>
</head>
<body>
    
    <div class="contenedor">
    
        <img class="logo" src="../assets/img/persona.png" alt="logo">
        <h1>Ingreso</h1>

        <form>

            <!-- Usuario -->
            <label for="usuario">Usuario</label>
            <input type="text" placeholder="Usuario">

            <!-- Contraseña -->
            <label for="contraseña">Contraseña</label>
            <input type="password" placeholder="Contraseña">

            <input class="BotonIngreso" type="submit" value="Ingresar">

        </form>

    </div>

</body>
</html>

<!-- "Somos lo que hacemos dia a dia de modo que la excelencia no es un acto, sino un hábito" - Aristóteles -->