<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../assets/css/sub_inicio.css">
    <title>Dirección</title>
</head>
<body>
    
    <div class="contenedor">
        <a class="ingresoL" href="../controlador/tipo_doc.php">Ingreso</a>
        <img class="ingreso" src="../assets/img/ingreso.png" alt="ingreso"><br>

        <a class="salidaL" href="pestañas/salida.phtml">Salida</a>
        <img class="salida" src="../assets/img/salida.png" alt="salida">

        <a class="registroL" href="pestañas/registro.phtml">Registros</a>
        <img class="registro" src="../assets/img/registro.png" alt="registro">
        
    </div>

</body>
</html>