<!DOCTYPE html>
<?php 

    session_start(); 
    require_once("../../config.php");
    $var_sesion = sesion_exitosa();

?>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../../assets/css/registros.css">
    <title>Dirección</title>
</head>
<body>
    
    <div class="contenedor">
    
        <a class="ingresoL" href="../../controlador/bitacora.php">Registro Ingreso</a>
        <img class="ingreso" src="../../assets/img/pdf.png" alt="datos"><br>

        <a class="salidaL" href="../../controlador/bitacora_salida.php">Registro Salida</a>
        <img class="salida" src="../../assets/img/pdf.png" alt="datos">

    </div>

</body>
</html>