<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../../assets/css/registros.css">
    <title>Dirección</title>
</head>
<body>
    
    <div class="contenedor">

        <a class="ingresoL" href="#">Registro Ingreso</a>
        <img class="ingreso" src="../../assets/img/pdf.png" alt="datos"><br>

        <a class="salidaL" href="#">Registro Salida</a>
        <img class="salida" src="../../assets/img/pdf.png" alt="datos">
        
    </div>

</body>
</html>