<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <div class="contenedor2">
        <table>
        
            <tr>
            
                <th>Nombre</th>
                <th>Documento</th>
                <th>Fecha : Hora</th>

            </tr>

            <?php
                while($datoss = mysqli_fetch_array($querys))
                { 
            ?>

            <tr>
            
            <td><?php echo $datoss['nombre_usuario']; ?></td>
            <td><?php echo $datoss['documento']; ?></td>
            <td><?php echo $datoss['fecha']; ?></td>

            </tr>

            <?php
                }
            ?>

        </table>
    </div>

</body>
</html>